/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as Customer_careIndexRouteImport } from './routes/customer_care/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as PaymentOpay_successRouteImport } from './routes/payment/opay_success'
import { Route as PaymentOpay_cancelRouteImport } from './routes/payment/opay_cancel'
import { Route as ApiVerify_emailRouteImport } from './routes/api/verify_email'
import { Route as ApiUserIdRouteImport } from './routes/api/user/$id'
import { Route as ApiOpayOpay_webhookRouteImport } from './routes/api/opay/opay_webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const Customer_careIndexRoute = Customer_careIndexRouteImport.update({
  id: '/customer_care/',
  path: '/customer_care/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentOpay_successRoute = PaymentOpay_successRouteImport.update({
  id: '/payment/opay_success',
  path: '/payment/opay_success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentOpay_cancelRoute = PaymentOpay_cancelRouteImport.update({
  id: '/payment/opay_cancel',
  path: '/payment/opay_cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerify_emailRoute = ApiVerify_emailRouteImport.update({
  id: '/api/verify_email',
  path: '/api/verify_email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserIdRoute = ApiUserIdRouteImport.update({
  id: '/api/user/$id',
  path: '/api/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpayOpay_webhookRoute = ApiOpayOpay_webhookRouteImport.update({
  id: '/api/opay/opay_webhook',
  path: '/api/opay/opay_webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/verify_email': typeof ApiVerify_emailRoute
  '/payment/opay_cancel': typeof PaymentOpay_cancelRoute
  '/payment/opay_success': typeof PaymentOpay_successRoute
  '/about/': typeof AboutIndexRoute
  '/customer_care/': typeof Customer_careIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/opay/opay_webhook': typeof ApiOpayOpay_webhookRoute
  '/api/user/$id': typeof ApiUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/verify_email': typeof ApiVerify_emailRoute
  '/payment/opay_cancel': typeof PaymentOpay_cancelRoute
  '/payment/opay_success': typeof PaymentOpay_successRoute
  '/about': typeof AboutIndexRoute
  '/customer_care': typeof Customer_careIndexRoute
  '/learn': typeof LearnIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/api/opay/opay_webhook': typeof ApiOpayOpay_webhookRoute
  '/api/user/$id': typeof ApiUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/verify_email': typeof ApiVerify_emailRoute
  '/payment/opay_cancel': typeof PaymentOpay_cancelRoute
  '/payment/opay_success': typeof PaymentOpay_successRoute
  '/about/': typeof AboutIndexRoute
  '/customer_care/': typeof Customer_careIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/opay/opay_webhook': typeof ApiOpayOpay_webhookRoute
  '/api/user/$id': typeof ApiUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/verify_email'
    | '/payment/opay_cancel'
    | '/payment/opay_success'
    | '/about/'
    | '/customer_care/'
    | '/learn/'
    | '/login/'
    | '/profile/'
    | '/api/opay/opay_webhook'
    | '/api/user/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/verify_email'
    | '/payment/opay_cancel'
    | '/payment/opay_success'
    | '/about'
    | '/customer_care'
    | '/learn'
    | '/login'
    | '/profile'
    | '/api/opay/opay_webhook'
    | '/api/user/$id'
  id:
    | '__root__'
    | '/'
    | '/api/verify_email'
    | '/payment/opay_cancel'
    | '/payment/opay_success'
    | '/about/'
    | '/customer_care/'
    | '/learn/'
    | '/login/'
    | '/profile/'
    | '/api/opay/opay_webhook'
    | '/api/user/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiVerify_emailRoute: typeof ApiVerify_emailRoute
  PaymentOpay_cancelRoute: typeof PaymentOpay_cancelRoute
  PaymentOpay_successRoute: typeof PaymentOpay_successRoute
  AboutIndexRoute: typeof AboutIndexRoute
  Customer_careIndexRoute: typeof Customer_careIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ApiOpayOpay_webhookRoute: typeof ApiOpayOpay_webhookRoute
  ApiUserIdRoute: typeof ApiUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer_care/': {
      id: '/customer_care/'
      path: '/customer_care'
      fullPath: '/customer_care/'
      preLoaderRoute: typeof Customer_careIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/opay_success': {
      id: '/payment/opay_success'
      path: '/payment/opay_success'
      fullPath: '/payment/opay_success'
      preLoaderRoute: typeof PaymentOpay_successRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/opay_cancel': {
      id: '/payment/opay_cancel'
      path: '/payment/opay_cancel'
      fullPath: '/payment/opay_cancel'
      preLoaderRoute: typeof PaymentOpay_cancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify_email': {
      id: '/api/verify_email'
      path: '/api/verify_email'
      fullPath: '/api/verify_email'
      preLoaderRoute: typeof ApiVerify_emailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/$id': {
      id: '/api/user/$id'
      path: '/api/user/$id'
      fullPath: '/api/user/$id'
      preLoaderRoute: typeof ApiUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/opay/opay_webhook': {
      id: '/api/opay/opay_webhook'
      path: '/api/opay/opay_webhook'
      fullPath: '/api/opay/opay_webhook'
      preLoaderRoute: typeof ApiOpayOpay_webhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiVerify_emailRoute: ApiVerify_emailRoute,
  PaymentOpay_cancelRoute: PaymentOpay_cancelRoute,
  PaymentOpay_successRoute: PaymentOpay_successRoute,
  AboutIndexRoute: AboutIndexRoute,
  Customer_careIndexRoute: Customer_careIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ApiOpayOpay_webhookRoute: ApiOpayOpay_webhookRoute,
  ApiUserIdRoute: ApiUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
